config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :subscriptions
  root 'subscriptions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status:  :not_found, layout: false
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_action :set_subscription, only: %i[show destroy edit update]

  def index
    @subscriptions = Subscription.order(created_at: :desc)
  end

  def show
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new subscription_params

    if @subscription.save
      redirect_to subscriptions_path
    else
      render :new
    end
  end

  def destroy
    @subscription.destroy
    redirect_to subscriptions_path
  end

  def edit
  end

  def update
    if @subscription.update subscription_params
      redirect_to subscriptions_path
    else
      render :edit
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :price)
  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubscriptionTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "application" %>
</head>

<body>
<div class="container mx-auto">
  <%= yield %>
</div>
</body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_with model: @subscription do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.select :currency, %i[₽ $ € ￡] %>

  <%= f.check_box :trial %>
  <%= f.label :trial %>

  <%= f.label :bill_date %>
  <%= f.date_select :bill_date %>

  <%= f.label :cycle, 'Every' %>
  <%= f.select :cycle, %i[month year] %>

  <%= f.label :duration %>
  <%= f.date_select :duration %>

  <%= f.label :reminder %>
  <%= f.date_select :reminder %>

  <%= f.label :subscription_type %>
  <%= f.select :subscription_type, %i[Individual Family Business] %>

  <%= f.submit %>
<% end %>

app/views/subscriptions/edit.html.erb
<h2>Edit <%= @subscription.name %></h2>

<%= render 'subscriptions/form' %>

app/views/subscriptions/index.html.erb
<h1>Subscriptions</h1>

<% @subscriptions.each do |subscription| %>
  <h2 class="text-2xl"><%= link_to subscription.name, subscription %> </h2>
  <p><%= subscription.price %></p>
<% end %>

<%= link_to "Add subscription", new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= form_with model: @subscription do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.number_field :price %>


<% end %>

app/views/subscriptions/show.html.erb
<%= link_to 'All subscription', root_path %>

<h1><%= @subscription.name %></h1>
<p><%= @subscription.price %></p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %>
<%= link_to 'Destroy', @subscription, method: :delete %>